import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/cartContext";
import WishlistContextProvider from "@/components/context/wishlistContext";

import { SessionProvider } from "next-auth/react";
import MysessionProvider from "@/components/mySessionProvider/MysessionProvider";
import Footer from "@/components/footer/pages";
import { WishlistContext } from "@/components/context/wishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        
<MysessionProvider>



<WishlistContextProvider>




<CartContextProvider>







<Navbar/>
  
      <div className="container w-5/6 mx-auto">
{children}
<Toaster/>
      </div>
<Footer/>
  
</CartContextProvider>

       
</WishlistContextProvider>

      </MysessionProvider>
    
        
      </body>
    </html>
  );
}
